export const krBankList = [
    { value: "002", name: "산업은행" },
    { value: "003", name: "기업은행" },
    { value: "004", name: "KB국민은행" },
    { value: "007", name: "수협은행" },
    { value: "011", name: "NH농협은행" },
    { value: "012", name: "농협중앙회(단위농협)" },
    { value: "020", name: "우리은행" },
    { value: "023", name: "SC제일은행" },
    { value: "027", name: "한국씨티" },
    { value: "031", name: "대구은행" },
    { value: "032", name: "부산은행" },
    { value: "034", name: "광주은행" },
    { value: "035", name: "제주은행" },
    { value: "037", name: "전북은행" },
    { value: "039", name: "경남은행" },
    { value: "045", name: "새마을금고중앙회" },
    { value: "048", name: "신협중앙회" },
    { value: "064", name: "산림조합중앙회" },
    { value: "071", name: "우체국" },
    { value: "081", name: "하나은행" },
    { value: "088", name: "신한은행" },
    { value: "089", name: "케이뱅크" },
    { value: "090", name: "카카오뱅크" },
    { value: "092", name: "토스뱅크" },
];

